name: dart_openai
description: Dart SDK for openAI Apis (GPT-3 & DALL-E), integrate easily the power of OpenAI's state-of-the-art AI models into their Dart applications.
version: 5.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  # https://pub.dev/packages/http
  http: ^1.2.2
  # https://pub.dev/packages/meta
  meta: ^1.16.0
  # https://pub.dev/packages/collection
  collection: ^1.19.1
  # https://pub.dev/packages/fetch_client
  fetch_client: ^1.1.2
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5

dev_dependencies:
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.13
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.8.0
  # https://pub.dev/packages/lint
  lint: ^2.3.0
  # https://pub.dev/packages/test
  test: ^1.25.8
