import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';

part 'choice.g.dart';

/// {@template openai_edit_model_choice}
/// This class is used to represent a choice generated by an OpenAI edit.
/// {@endtemplate}
@immutable
@JsonSerializable()
final class OpenAIEditModelChoice extends Equatable {
  /// {@macro openai_edit_model_choice}
  const OpenAIEditModelChoice({
    required this.text,
    required this.index,
  });

  /// {@macro openai_edit_model_choice}
  /// This method is used to convert a [Map<String, dynamic>] object to a [OpenAIEditModelChoice] object.
  factory OpenAIEditModelChoice.fromJson(Map<String, dynamic> json) =>
      _$OpenAIEditModelChoiceFromJson(json);

  /// Converts this object to a JSON map.
  Map<String, dynamic> toJson() => _$OpenAIEditModelChoiceToJson(this);

  /// The text of the choice.
  @JsonKey(name: 'text') // Add this if the API returns "_text"
  final String text;

  /// The index of the choice.
  @JsonKey(name: 'index') // Add this if the API returns "_index"
  final int index;

  @override
  List<Object?> get props => [text, index];

  @override
  String toString() => 'OpenAIEditModelChoice(text: $text, index: $index)';
}
